In [5]:
import numpy as np
import cv2

In [6]:
degree = 45
center = (0, 0)
M = cv2.getRotationMatrix2D(center, degree, 1)

In [7]:
M

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ]])

In [8]:
p = np.asarray([10, 10, 1])

In [11]:
M.shape

(2, 3)

In [12]:
p.shape

(3,)

In [13]:
np.matmul(M, p)

array([  1.41421356e+01,   8.88178420e-16])

In [14]:
a = [[1,2],[3,4]]

In [15]:
np.asarray(a)

array([[1, 2],
       [3, 4]])